"""GitHub PR creation with rich daily-run body"""
import json
import subprocess
from pathlib import Path
from datetime import datetime

PROJECT_ROOT = Path(__file__).parent.parent.parent

VERTICAL_LABELS = {
    "edge-power-ups": "Edge & UPS",
    "data-centers": "Data Centers",
    "building-electrification": "Building Electrification",
}


def _load_json_safe(path):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return None


def build_daily_pr_body(run_stats=None):
    """
    Build a rich PR body from daily run stats and today's artifact files.
    run_stats: dict from run_normalize() — new_pulse, skipped, new_items,
               skip_reasons, by_vertical. Optional; artifacts are always read.
    """
    today = datetime.now().strftime("%Y-%m-%d")
    lines = [f"## Daily update — {today}", ""]

    # ── Pulse counts ─────────────────────────────────────────────────────────
    if run_stats:
        new_pulse  = run_stats.get("new_pulse", run_stats.get("added", 0))
        skipped    = run_stats.get("skipped", 0)
        by_vertical = run_stats.get("by_vertical", {})
        skip_reasons = run_stats.get("skip_reasons", {})

        lines.append("### Pulse counts")
        lines.append(f"- **{new_pulse}** new item(s) added, {skipped} dropped")

        if by_vertical:
            for key, count in sorted(by_vertical.items()):
                label = VERTICAL_LABELS.get(key, key)
                lines.append(f"  - {label}: {count}")

        if skip_reasons:
            parts = []
            for reason, count in skip_reasons.items():
                if count:
                    parts.append(f"{reason.replace('_', ' ')}: {count}")
            if parts:
                lines.append(f"- Drop reasons: {', '.join(parts)}")
        lines.append("")

        # ── Top 5 new items ───────────────────────────────────────────────────
        new_items = run_stats.get("new_items", [])
        if new_items:
            lines.append("### Top new items")
            top5 = sorted(new_items, key=lambda x: x.get("score", 0), reverse=True)[:5]
            for item in top5:
                so_what = f"  \n  *{item['so_what']}*" if item.get("so_what") else ""
                lines.append(f"- **{item['title'][:90]}**{so_what}")
            lines.append("")

    # ── Insights ─────────────────────────────────────────────────────────────
    moderator = _load_json_safe(
        PROJECT_ROOT / "data" / "insights" / f"{today}_moderator.json"
    )
    if moderator:
        insights = moderator.get("composite_insights", [])
        if insights:
            lines.append("### Top insights")
            for insight in insights[:2]:
                lever = insight.get("lever", "")
                lever_str = f" `[{lever}]`" if lever else ""
                lines.append(f"- {insight.get('insight', '')[:220]}{lever_str}")
            lines.append("")

        angles = moderator.get("ranked_angles", [])
        if angles:
            top = angles[0]
            lines.append("### Top original angle")
            lines.append(f"**{top.get('title', '')}**  ")
            lines.append(top.get("thesis", ""))
            if top.get("owner_questions"):
                lines.append(f"*Owner question: {top['owner_questions'][0]}*")
            lines.append("")

    # ── Social drafts ─────────────────────────────────────────────────────────
    social = _load_json_safe(
        PROJECT_ROOT / "data" / "social" / f"{today}_social_drafts.json"
    )
    if social:
        li = len(social.get("linkedin_drafts", []))
        x  = len(social.get("x_drafts", []))
        lines.append("### Social drafts")
        lines.append(f"- {li} LinkedIn, {x} X drafts in `data/social/{today}_social_drafts.json`")
        lines.append("")

    lines += ["---", "_Generated by FMP Bot_"]
    return "\n".join(lines)


def open_pr(title, body=None):
    """Open a PR using gh CLI. Returns PR URL or None."""
    try:
        cmd = ["gh", "pr", "create", "--title", title,
               "--body", body or "Automated content update"]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            url = result.stdout.strip()
            print(f"PR created: {url}")
            return url
        else:
            print(f"Error creating PR: {result.stderr.strip()}")
            return None
    except Exception as e:
        print(f"Error: {e}")
        return None


def open_daily_pr(run_stats=None):
    """
    Open the daily PR with a rich auto-built body.
    run_stats: optional dict from run_normalize().
    Returns PR URL or None.
    """
    today = datetime.now().strftime("%Y-%m-%d")
    new_pulse = 0
    if run_stats:
        new_pulse = run_stats.get("new_pulse", run_stats.get("added", 0))

    # Count insights + social for PR title
    moderator = _load_json_safe(
        PROJECT_ROOT / "data" / "insights" / f"{today}_moderator.json"
    )
    n_insights = len(moderator.get("composite_insights", [])) if moderator else 0

    social = _load_json_safe(
        PROJECT_ROOT / "data" / "social" / f"{today}_social_drafts.json"
    )
    n_social = 0
    if social:
        n_social = len(social.get("linkedin_drafts", [])) + len(social.get("x_drafts", []))

    title = f"Daily update: {today} ({new_pulse} pulse, {n_insights} insights, {n_social} social)"
    body = build_daily_pr_body(run_stats)
    return open_pr(title, body)
